"""Builder node — executes tasks via Cline CLI inside Docker containers."""

from __future__ import annotations

import logging
import shlex
import time

from orchestrator.config import settings
from orchestrator.docker_engine.manager import ContainerManager
from orchestrator.graph.state import AutomatronState
from orchestrator.llm.configuration import default_llm_config, normalize_llm_config
from orchestrator.plan_parser.parser import get_global_rules

logger = logging.getLogger(__name__)

container_manager = ContainerManager()


async def builder_node(state: AutomatronState) -> dict:
    """Run the current task in the project container."""
    container_id = state.get("container_id", "")
    task_text = state.get("current_task_text", "")
    task_index = state.get("current_task_index", -1)
    plan_md = state.get("plan_md", "")
    llm_config = normalize_llm_config(state.get("llm_config") or default_llm_config())
    builder_model_name = llm_config["builder"]["model"]
    project_name = state.get("project_name", "Automatron Project")
    intake_text = state.get("intake_text", "")

    if not container_id:
        return {
            "builder_status": "BLOCKER",
            "builder_error_detail": "No Docker container available",
            "builder_output": "",
            "project_stage": "building",
            "status": "building",
        }
    if not task_text:
        return {
            "builder_status": "BLOCKER",
            "builder_error_detail": "No task text provided",
            "builder_output": "",
            "project_stage": "building",
            "status": "building",
        }

    global_rules = get_global_rules(plan_md)
    rules_text = "\n".join(f"- {rule}" for rule in global_rules) if global_rules else "- None"
    stack_config = state.get("stack_config", {})
    preview_port = state.get("container_port", 3000)
    preview_requirement = (
        "By the end of the plan, the repo must contain Dockerfile, .env.example, "
        "deploy/docker-compose.yml, DEPLOY.md, .github/workflows/ci.yml, "
        "and .github/workflows/deploy.yml. Preview must be able to run on the allocated port."
    )

    cline_prompt = (
        "You are Automatron Builder operating inside the project workspace.\n\n"
        f"PROJECT NAME:\n{project_name}\n\n"
        f"PROJECT INTAKE:\n{intake_text}\n\n"
        f"CURRENT TASK:\n{task_text}\n\n"
        f"STACK CONFIG:\n{stack_config}\n\n"
        f"GLOBAL RULES:\n{rules_text}\n\n"
        "REQUIRED OUTPUT CONTRACT:\n"
        f"- {preview_requirement}\n"
        f"- The active preview port is {preview_port}\n"
        "- For Next.js web apps, expose a GET `/api/health` endpoint that returns JSON and verifies core dependencies such as the database when they exist\n"
        "- Replace default scaffold metadata like `Create Next App` and `Generated by create next app` with project-specific title and description\n"
        "- Keep PLAN.md in sync with completed tasks\n"
        "- Do not remove the existing git repository\n"
        "- Preserve the generated GitHub Actions workflows unless intentionally updating them\n"
        "- Do not access external deployment credentials\n"
        "- Inspect the installed Prisma major version before changing Prisma setup\n"
        "- For Prisma 5 projects, keep a valid `url` inside the `datasource db` block in `prisma/schema.prisma`\n"
        "- For Prisma 7 projects, create `prisma.config.ts` or `prisma.config.js` in `/workspace`, never in `/workspace/prisma`\n"
        "- When creating Prisma 7 config, import `defineConfig` from `prisma/config`, not `@prisma/internals`\n"
        "- Do not start long-running foreground processes like `next dev`, `npm run dev`, `vite`, or database studios unless the current task explicitly requires a preview server\n"
        "- For verification during normal build tasks, prefer one-shot commands like `npm run build`, `npm run lint`, route-level tests, or commands wrapped with `timeout`\n"
    )

    try:
        await container_manager.copy_file_to_container(container_id, plan_md, "/workspace/PLAN.md")
        await container_manager.copy_file_to_container(
            container_id,
            cline_prompt,
            "/tmp/automatron_task_prompt.txt",
        )
    except Exception as exc:
        return {
            "builder_status": "BLOCKER",
            "builder_output": str(exc),
            "builder_error_detail": f"Failed to prepare Cline prompt: {exc}",
            "project_stage": "building",
            "status": "building",
        }

    model = shlex.quote(builder_model_name)
    timeout = settings.builder_cline_timeout
    shell_guards = (
        "AUTOMATRON_ALLOW_DEV_SERVER=0; "
        'next(){ if [ "${1:-}" = "dev" ] && [ "${AUTOMATRON_ALLOW_DEV_SERVER:-0}" != "1" ]; then '
        'echo "[Automatron] next dev is reserved for preview stage"; return 97; fi; command next "$@"; }; '
        'npm(){ if [ "${1:-}" = "run" ] && [ "${2:-}" = "dev" ] && [ "${AUTOMATRON_ALLOW_DEV_SERVER:-0}" != "1" ]; then '
        'echo "[Automatron] npm run dev is reserved for preview stage"; return 97; fi; command npm "$@"; }; '
        'pnpm(){ if [ "${1:-}" = "dev" ] && [ "${AUTOMATRON_ALLOW_DEV_SERVER:-0}" != "1" ]; then '
        'echo "[Automatron] pnpm dev is reserved for preview stage"; return 97; fi; command pnpm "$@"; }; '
        'yarn(){ if [ "${1:-}" = "dev" ] && [ "${AUTOMATRON_ALLOW_DEV_SERVER:-0}" != "1" ]; then '
        'echo "[Automatron] yarn dev is reserved for preview stage"; return 97; fi; command yarn "$@"; }; '
        "export -f next npm pnpm yarn; "
    )
    command = (
        f"{shell_guards}"
        f"PROMPT=$(cat /tmp/automatron_task_prompt.txt) && "
        f"cline task -y --json -m {model} -t {timeout} "
        '--cwd /workspace "$PROMPT"'
    )

    started = time.monotonic()
    try:
        result = await container_manager.exec_in_container(container_id, command, timeout=timeout + 30)
        output = result.output
        exit_code = result.exit_code
    except Exception as exc:
        return {
            "builder_status": "BLOCKER",
            "builder_output": str(exc),
            "builder_error_detail": f"Cline execution failed: {exc}",
            "builder_duration_s": time.monotonic() - started,
            "project_stage": "building",
            "status": "building",
        }

    updated_plan = plan_md
    try:
        updated_plan = await container_manager.read_file_from_container(container_id, "/workspace/PLAN.md")
    except Exception as exc:
        logger.warning("Could not read PLAN.md after task %d: %s", task_index, exc)

    return {
        "builder_output": output,
        "builder_error_detail": "" if exit_code == 0 else output[-2000:],
        "builder_exit_code": exit_code,
        "builder_duration_s": time.monotonic() - started,
        "plan_md": updated_plan,
        "project_stage": "building",
        "status": "building",
    }
